name: build Docker Image

on: 
  workflow_dispatch:
    branches: 
      - main
env: 
  DOCKER_PASSWORD: ${{ secrets.test }} 

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u baptistebeugin -p ${{ secrets.test }}

    - name: build image
      run: |
        docker build -t baptistebeugin/docker:latest .
    - name: Docker push
      run: |
        docker push baptistebeugin/docker:latest